services:
  # postgres
  db:
    image: postgres:15-alpine
    container_name: postgres_db_ss
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # rabbitmq
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_ss
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
  # s3 storage
  minio:
    image: minio/minio:latest
    container_name: minio_ss
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  # backend
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    container_name: gateway_ss
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql+asyncpg://test:test@db:5432/test_db"
      RABBITMQ_URL: "amqp://test:test@rabbitmq:5672/"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "test"
      MINIO_SECRET_KEY: "test_minio"
  # backend-worker
  ml_worker:
    build: ./ml_worker
    container_name: ml_worker_ss
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql+psycopg2://test:test@db:5432/test_db"
      RABBITMQ_URL: "amqp://test:test@rabbitmq:5672/"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "test"
      MINIO_SECRET_KEY: "test_minio"
  # frontend
  frontend:
    build: ./frontend
    container_name: frontend_ss
    restart: always
    ports:
      - "3000:80"
volumes:
  postgres_data:
  rabbitmq_data:
  minio_data: